version: '3'

networks:

  default:

services: 

  cluster:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 6006:6006
      - 8888:8888
    volumes:
      - .:/service
    networks:
      - default
    tty: true

