version: '3'

networks:

  default:

services: 

  cluster:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./tests/:/service
    networks:
      - default
    tty: true

